name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v2
      - uses: yoshi389111/github-profile-3d-contrib@0.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          echo "Starting commit and push process..."
          git config user.name ChocoCoffee999
          echo "Configured git user name"
          git config user.email kim99602@naver.com
          echo "Configured git user email"
          git fetch origin master
          echo "Fetched origin master"
          git merge origin/master
          echo "Merged origin/master"
          git add -A .
          echo "Staged changes"
          git commit -m "generated"
          echo "Committed changes"
          git push --force origin master
          echo "Pushed changes"
